CREATE TABLE `demarcation_site_link` (
    `date` VARCHAR(20) DEFAULT NULL,
    `siteid` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    `city` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
    `region` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
    `longitude` double DEFAULT NULL,
    `latitude` double DEFAULT NULL,
    `level_ne_a` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `ne_a` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `interface_a` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `TLP_a` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `site_destination` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `ne_b` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `interface_b` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `TLP_b` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `longitude_destination` double DEFAULT NULL,
    `latitude_destination` double DEFAULT NULL,
    `level_ne_b` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
    `link` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
    `type_transport` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
    `bandwith` double DEFAULT NULL,
    `max_util` double DEFAULT NULL,
    `capacity` double DEFAULT NULL,
    `ioh_data_traffic_4g` double DEFAULT NULL,
    `availability` double DEFAULT NULL,
    `eut` double DEFAULT NULL,
    `cqi` double DEFAULT NULL,
    `prb` double DEFAULT NULL,
    `accesibility` double DEFAULT NULL,
    `s1_sr` double DEFAULT NULL,
    `erab_drop` double DEFAULT NULL,
    `rrc_sr` double DEFAULT NULL,
    `erab_sr` double DEFAULT NULL,
    `inter_freq` double DEFAULT NULL,
    `intra_freq` double DEFAULT NULL,
    `irat_hosr` double DEFAULT NULL,
    `ul_rssi` double DEFAULT NULL,
    `SE_DL` double DEFAULT NULL,
    `csfb_prep_sr` double DEFAULT NULL,
    `csfb_sr` double DEFAULT NULL,
    `syn_ack_ack_delay` double DEFAULT NULL,
    `syn_syn_ack_delay` double DEFAULT NULL,
    `downlink_tcp_retransmission_rate` double DEFAULT NULL,
    `traffic_origin` double DEFAULT NULL,
    `availability_origin` double DEFAULT NULL,
    `eut_origin` double DEFAULT NULL,
    `cqi_origin` double DEFAULT NULL,
    `prb_origin` double DEFAULT NULL,
    `accesibility_origin` double DEFAULT NULL,
    `s1_sr_origin` double DEFAULT NULL,
    `erab_drop_origin` double DEFAULT NULL,
    `RRC_SR_origin` double DEFAULT NULL,
    `erab_sr_origin` double DEFAULT NULL,
    `inter_freq_origin` double DEFAULT NULL,
    `intra_freq_origin` double DEFAULT NULL,
    `irat_hosr_origin` double DEFAULT NULL,
    `ul_rssi_origin` double DEFAULT NULL,
    `SE_DL_origin` double DEFAULT NULL,
    `csfb_prep_sr_origin` double DEFAULT NULL,
    `csfb_sr_origin` double DEFAULT NULL,
    `syn_ack_ack_delay_origin` double DEFAULT NULL,
    `syn_syn_ack_delay_origin` double DEFAULT NULL,
    `downlink_tcp_retransmission_rate_origin` double DEFAULT NULL,
    KEY `idx_city` (`city`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3 COMMENT = 'Not Available';

CREATE TABLE topo_link (
    siteid VARCHAR(50) not NULL,
    interface_a VARCHAR(100) not NULL,
    TLP_a VARCHAR(100) not NULL,
    city VARCHAR(100) not NULL,
    longitude double NULL,
    latitude double NULL,
    ne_a VARCHAR(100) not NULL,
    ne_b VARCHAR(100) not NULL,
    site_destination VARCHAR(50) not NULL,
    interface_b VARCHAR(100) not NULL,
    TLP_b VARCHAR(100) not NULL,
    longitude_destination double NULL,
    latitude_destination double NULL,
    link VARCHAR(100) not NULL,
    type_transport VARCHAR(20) not NULL,
    level_ne_a VARCHAR(50) not NULL,
    level_ne_b VARCHAR(50) not NULL,
    bandwith double NULL,
    max_util double NULL,
    capacity double NULL,
    INDEX idx_city (city)
);