// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository


type DemarcationSiteLink struct {
	Date                                *string          `json:"date"`
	Siteid                              *string          `json:"siteid"`
	City                                *string          `json:"city"`
	Region                              *string          `json:"region"`
	RanSiteLongitude                    *float64 `json:"ran_site_longitude"`
	RanSiteLatitude                     *float64 `json:"ran_site_latitude"`
	SiteDestination                     *string          `json:"site_destination"`
	LongitudeDestination                *float64 `json:"longitude_destination"`
	LatitudeDestination                 *float64 `json:"latitude_destination"`
	Link                                *string          `json:"link"`
	TypeTransport                       *string          `json:"type_transport"`
	Interface                           *string          `json:"interface"`
	Tlp                                 *string          `json:"tlp"`
	IohDataTraffic4g                    *float64 `json:"ioh_data_traffic_4g"`
	Availability                        *float64 `json:"availability"`
	Eut                                 *float64 `json:"eut"`
	Cqi                                 *float64 `json:"cqi"`
	Prb                                 *float64 `json:"prb"`
	Accesibility                        *float64 `json:"accesibility"`
	S1Sr                                *float64 `json:"s1_sr"`
	ErabDrop                            *float64 `json:"erab_drop"`
	RrcSr                               *float64 `json:"rrc_sr"`
	ErabSr                              *float64 `json:"erab_sr"`
	InterFreq                           *float64 `json:"inter_freq"`
	IntraFreq                           *float64 `json:"intra_freq"`
	IratHosr                            *float64 `json:"irat_hosr"`
	UlRssi                              *float64 `json:"ul_rssi"`
	SeDl                                *float64 `json:"se_dl"`
	CsfbPrepSr                          *float64 `json:"csfb_prep_sr"`
	CsfbSr                              *float64 `json:"csfb_sr"`
	SynAckAckDelay                      *float64 `json:"syn_ack_ack_delay"`
	SynSynAckDelay                      *float64 `json:"syn_syn_ack_delay"`
	DownlinkTcpRetransmissionRate       *float64 `json:"downlink_tcp_retransmission_rate"`
	MaxUtil                             *float64 `json:"max_util"`
	Capacity                            *float64 `json:"capacity"`
	TrafficOrigin                       *float64 `json:"traffic_origin"`
	AvailabilityOrigin                  *float64 `json:"availability_origin"`
	EutOrigin                           *float64 `json:"eut_origin"`
	CqiOrigin                           *float64 `json:"cqi_origin"`
	PrbOrigin                           *float64 `json:"prb_origin"`
	AccesibilityOrigin                  *float64 `json:"accesibility_origin"`
	S1SrOrigin                          *float64 `json:"s1_sr_origin"`
	ErabDropOrigin                      *float64 `json:"erab_drop_origin"`
	RrcSrOrigin                         *float64 `json:"rrc_sr_origin"`
	ErabSrOrigin                        *float64 `json:"erab_sr_origin"`
	InterFreqOrigin                     *float64 `json:"inter_freq_origin"`
	IntraFreqOrigin                     *float64 `json:"intra_freq_origin"`
	IratHosrOrigin                      *float64 `json:"irat_hosr_origin"`
	UlRssiOrigin                        *float64 `json:"ul_rssi_origin"`
	SeDlOrigin                          *float64 `json:"se_dl_origin"`
	CsfbPrepSrOrigin                    *float64 `json:"csfb_prep_sr_origin"`
	CsfbSrOrigin                        *float64 `json:"csfb_sr_origin"`
	SynAckAckDelayOrigin                *float64 `json:"syn_ack_ack_delay_origin"`
	SynSynAckDelayOrigin                *float64 `json:"syn_syn_ack_delay_origin"`
	DownlinkTcpRetransmissionRateOrigin *float64 `json:"downlink_tcp_retransmission_rate_origin"`
}

type TopoLink struct {
	Siteid               *string  `json:"siteid"`
	InterfaceA           *string  `json:"interface_a"`
	TlpA                 *string  `json:"tlp_a"`
	City                 *string  `json:"city"`
	Longitude            *float64 `json:"longitude"`
	Latitude             *float64 `json:"latitude"`
	NeA                  *string  `json:"ne_a"`
	NeB                  *string  `json:"ne_b"`
	SiteDestination      *string  `json:"site_destination"`
	InterfaceB           *string  `json:"interface_b"`
	TlpB                 *string  `json:"tlp_b"`
	LongitudeDestination *float64 `json:"longitude_destination"`
	LatitudeDestination  *float64 `json:"latitude_destination"`
	Link                 *string  `json:"link"`
	TypeTransport        *string  `json:"type_transport"`
	LevelNeA             *string  `json:"level_ne_a"`
	LevelNeB             *string  `json:"level_ne_b"`
	Bandwith             *float64 `json:"bandwith"`
	MaxUtil              *float64 `json:"max_util"`
	Capacity             *float64 `json:"capacity"`
}
